### PR TITLE
Added custom server prefix feature!

### PR DESCRIPTION
**Pull request by ghost**
Now if you run the command: `{prefix}prefix ;`
It will change the bot prefix for THAT particular server/guild to `;`.
To reset you can do, `;prefix {prefix}`

### CODE REVIEW

**Comment by ghost** [comment]
@shadowolfyt, can you please either merge or close the pull request?

**Comment by benrobson** [comment]
Hey,
I am currently just taking a look around at the package you're using since I've never used before.
Just working with it a bit and adding some additional things.

**Comment by benrobson** [comment]
Got a question, how do I install the package? It's giving me a ton of errors.

**Comment by ghost** [comment]
> Got a question, how do I install the package? It's giving me a ton of errors.
Hello @shadowolfyt,
Check out the [Installation Guide](https://github.com/endb/endb#installation) on the GitHub.

**Comment by benrobson** [comment]
I checked out the installation guide and did the required steps and it's not working.
It's giving me `Error: Cannot find module 'endb'`

**Comment by ghost** [comment]
> I checked out the installation guide and did the required steps and it's not working.
> It's giving me `Error: Cannot find module 'endb'`

Hey @shadowolfyt,
Can you send me the output/message that appears when you install the package?
Furthermore, can you change the version to `0.0.13`?

**Pull request merged**
